/**
 * Magic Sort - 50 Verified Solvable Levels
 * Generated by generate_levels.py (Compliance: rules.md)
 * Version: 1.1.0 (Chunk-Move Rule & MaxScore Supported)
 */

const COLOR_PALETTE = {
  "orange": {
    "name": "Orange",
    "hex": "#e66025",
    "darkHex": "#b03e0e"
  },
  "yellow": {
    "name": "Yellow",
    "hex": "#f5b316",
    "darkHex": "#b87c05"
  },
  "maroon": {
    "name": "Maroon",
    "hex": "#4a121a",
    "darkHex": "#2e060c"
  },
  "brown": {
    "name": "Brown",
    "hex": "#7d5d42",
    "darkHex": "#4f3724"
  },
  "white": {
    "name": "White",
    "hex": "#e8e5de",
    "darkHex": "#aba8a0"
  },
  "red": {
    "name": "Red",
    "hex": "#dc3545",
    "darkHex": "#9b1825"
  },
  "blue": {
    "name": "Blue",
    "hex": "#1d72b8",
    "darkHex": "#0e4a7b"
  },
  "teal": {
    "name": "Teal",
    "hex": "#009688",
    "darkHex": "#005a52"
  },
  "purple": {
    "name": "Purple",
    "hex": "#8e44ad",
    "darkHex": "#5b2474"
  },
  "green": {
    "name": "Green",
    "hex": "#27ae60",
    "darkHex": "#186d3b"
  },
  "pink": {
    "name": "Pink",
    "hex": "#e84393",
    "darkHex": "#a22160"
  },
  "cyan": {
    "name": "Cyan",
    "hex": "#00cec9",
    "darkHex": "#008a86"
  }
};

const LEVELS_DATA = [
  {
    "level": 1,
    "colorsCount": 2,
    "emptyBottles": 1,
    "minMoves": 3,
    "maxScore": 2400,
    "bottles": [
      [
        "orange",
        "orange",
        "yellow",
        "yellow"
      ],
      [
        "yellow",
        "yellow",
        "orange",
        "orange"
      ],
      []
    ]
  },
  {
    "level": 2,
    "colorsCount": 2,
    "emptyBottles": 1,
    "minMoves": 7,
    "maxScore": 2800,
    "bottles": [
      [
        "orange",
        "yellow",
        "orange",
        "yellow"
      ],
      [
        "yellow",
        "orange",
        "yellow",
        "orange"
      ],
      []
    ]
  },
  {
    "level": 3,
    "colorsCount": 3,
    "emptyBottles": 1,
    "minMoves": 9,
    "maxScore": 3200,
    "bottles": [
      [
        "orange",
        "yellow",
        "maroon",
        "maroon"
      ],
      [
        "yellow",
        "maroon",
        "orange",
        "yellow"
      ],
      [
        "maroon",
        "orange",
        "yellow",
        "orange"
      ],
      []
    ]
  },
  {
    "level": 4,
    "colorsCount": 3,
    "emptyBottles": 2,
    "minMoves": 5,
    "maxScore": 3600,
    "bottles": [
      [
        "orange",
        "orange",
        "orange",
        "yellow"
      ],
      [
        "yellow",
        "maroon",
        "maroon",
        "maroon"
      ],
      [
        "maroon",
        "orange",
        "yellow",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 5,
    "colorsCount": 3,
    "emptyBottles": 2,
    "minMoves": 7,
    "maxScore": 4000,
    "bottles": [
      [
        "orange",
        "maroon",
        "maroon",
        "orange"
      ],
      [
        "orange",
        "yellow",
        "yellow",
        "maroon"
      ],
      [
        "yellow",
        "yellow",
        "orange",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 6,
    "colorsCount": 3,
    "emptyBottles": 2,
    "minMoves": 6,
    "maxScore": 4400,
    "bottles": [
      [
        "yellow",
        "orange",
        "maroon",
        "maroon"
      ],
      [
        "yellow",
        "maroon",
        "yellow",
        "yellow"
      ],
      [
        "maroon",
        "orange",
        "orange",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 7,
    "colorsCount": 4,
    "emptyBottles": 2,
    "minMoves": 13,
    "maxScore": 4800,
    "bottles": [
      [
        "brown",
        "maroon",
        "orange",
        "maroon"
      ],
      [
        "brown",
        "yellow",
        "maroon",
        "brown"
      ],
      [
        "yellow",
        "maroon",
        "orange",
        "orange"
      ],
      [
        "yellow",
        "orange",
        "brown",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 8,
    "colorsCount": 4,
    "emptyBottles": 2,
    "minMoves": 11,
    "maxScore": 5200,
    "bottles": [
      [
        "brown",
        "brown",
        "maroon",
        "maroon"
      ],
      [
        "brown",
        "brown",
        "yellow",
        "orange"
      ],
      [
        "orange",
        "yellow",
        "orange",
        "maroon"
      ],
      [
        "maroon",
        "yellow",
        "orange",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 9,
    "colorsCount": 4,
    "emptyBottles": 2,
    "minMoves": 14,
    "maxScore": 5600,
    "bottles": [
      [
        "yellow",
        "orange",
        "yellow",
        "brown"
      ],
      [
        "yellow",
        "maroon",
        "orange",
        "maroon"
      ],
      [
        "brown",
        "orange",
        "maroon",
        "brown"
      ],
      [
        "orange",
        "yellow",
        "maroon",
        "brown"
      ],
      [],
      []
    ]
  },
  {
    "level": 10,
    "colorsCount": 4,
    "emptyBottles": 2,
    "minMoves": 11,
    "maxScore": 6000,
    "bottles": [
      [
        "brown",
        "brown",
        "maroon",
        "orange"
      ],
      [
        "orange",
        "maroon",
        "maroon",
        "orange"
      ],
      [
        "brown",
        "yellow",
        "yellow",
        "orange"
      ],
      [
        "yellow",
        "maroon",
        "brown",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 11,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 17,
    "maxScore": 6400,
    "bottles": [
      [
        "orange",
        "yellow",
        "brown",
        "orange"
      ],
      [
        "maroon",
        "brown",
        "white",
        "brown"
      ],
      [
        "white",
        "maroon",
        "brown",
        "yellow"
      ],
      [
        "maroon",
        "white",
        "maroon",
        "yellow"
      ],
      [
        "white",
        "yellow",
        "orange",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 12,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 15,
    "maxScore": 6800,
    "bottles": [
      [
        "orange",
        "maroon",
        "brown",
        "maroon"
      ],
      [
        "orange",
        "white",
        "yellow",
        "maroon"
      ],
      [
        "yellow",
        "yellow",
        "orange",
        "brown"
      ],
      [
        "brown",
        "orange",
        "white",
        "white"
      ],
      [
        "maroon",
        "yellow",
        "brown",
        "white"
      ],
      [],
      []
    ]
  },
  {
    "level": 13,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 12,
    "maxScore": 7200,
    "bottles": [
      [
        "brown",
        "white",
        "orange",
        "yellow"
      ],
      [
        "brown",
        "yellow",
        "maroon",
        "orange"
      ],
      [
        "yellow",
        "yellow",
        "maroon",
        "maroon"
      ],
      [
        "orange",
        "white",
        "white",
        "white"
      ],
      [
        "brown",
        "brown",
        "orange",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 14,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 13,
    "maxScore": 7600,
    "bottles": [
      [
        "orange",
        "orange",
        "maroon",
        "maroon"
      ],
      [
        "maroon",
        "orange",
        "yellow",
        "yellow"
      ],
      [
        "white",
        "white",
        "yellow",
        "orange"
      ],
      [
        "brown",
        "brown",
        "maroon",
        "brown"
      ],
      [
        "white",
        "yellow",
        "white",
        "brown"
      ],
      [],
      []
    ]
  },
  {
    "level": 15,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 12,
    "maxScore": 8000,
    "bottles": [
      [
        "white",
        "brown",
        "white",
        "brown"
      ],
      [
        "yellow",
        "yellow",
        "orange",
        "orange"
      ],
      [
        "orange",
        "yellow",
        "yellow",
        "maroon"
      ],
      [
        "maroon",
        "maroon",
        "brown",
        "white"
      ],
      [
        "brown",
        "orange",
        "white",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 16,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 16,
    "maxScore": 8400,
    "bottles": [
      [
        "white",
        "yellow",
        "yellow",
        "white"
      ],
      [
        "maroon",
        "yellow",
        "brown",
        "white"
      ],
      [
        "orange",
        "maroon",
        "brown",
        "white"
      ],
      [
        "orange",
        "orange",
        "brown",
        "orange"
      ],
      [
        "maroon",
        "brown",
        "yellow",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 17,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 12,
    "maxScore": 8800,
    "bottles": [
      [
        "yellow",
        "yellow",
        "yellow",
        "brown"
      ],
      [
        "white",
        "orange",
        "white",
        "maroon"
      ],
      [
        "brown",
        "white",
        "maroon",
        "maroon"
      ],
      [
        "orange",
        "yellow",
        "brown",
        "white"
      ],
      [
        "brown",
        "orange",
        "orange",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 18,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 13,
    "maxScore": 9200,
    "bottles": [
      [
        "brown",
        "maroon",
        "white",
        "white"
      ],
      [
        "white",
        "yellow",
        "white",
        "yellow"
      ],
      [
        "brown",
        "orange",
        "orange",
        "orange"
      ],
      [
        "maroon",
        "yellow",
        "yellow",
        "brown"
      ],
      [
        "brown",
        "orange",
        "maroon",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 19,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 15,
    "maxScore": 9600,
    "bottles": [
      [
        "orange",
        "yellow",
        "yellow",
        "orange"
      ],
      [
        "white",
        "maroon",
        "brown",
        "maroon"
      ],
      [
        "brown",
        "maroon",
        "yellow",
        "orange"
      ],
      [
        "white",
        "white",
        "orange",
        "white"
      ],
      [
        "yellow",
        "brown",
        "maroon",
        "brown"
      ],
      [],
      []
    ]
  },
  {
    "level": 20,
    "colorsCount": 5,
    "emptyBottles": 2,
    "minMoves": 16,
    "maxScore": 10000,
    "bottles": [
      [
        "brown",
        "maroon",
        "brown",
        "yellow"
      ],
      [
        "brown",
        "orange",
        "yellow",
        "maroon"
      ],
      [
        "orange",
        "maroon",
        "white",
        "maroon"
      ],
      [
        "white",
        "yellow",
        "white",
        "white"
      ],
      [
        "brown",
        "orange",
        "orange",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 21,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 18,
    "maxScore": 10400,
    "bottles": [
      [
        "maroon",
        "white",
        "maroon",
        "orange"
      ],
      [
        "brown",
        "white",
        "red",
        "maroon"
      ],
      [
        "yellow",
        "maroon",
        "brown",
        "brown"
      ],
      [
        "red",
        "white",
        "white",
        "yellow"
      ],
      [
        "orange",
        "red",
        "yellow",
        "red"
      ],
      [
        "orange",
        "yellow",
        "brown",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 22,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 20,
    "maxScore": 10800,
    "bottles": [
      [
        "yellow",
        "brown",
        "white",
        "red"
      ],
      [
        "white",
        "orange",
        "orange",
        "brown"
      ],
      [
        "yellow",
        "white",
        "brown",
        "maroon"
      ],
      [
        "yellow",
        "red",
        "orange",
        "maroon"
      ],
      [
        "red",
        "white",
        "red",
        "orange"
      ],
      [
        "maroon",
        "yellow",
        "brown",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 23,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 18,
    "maxScore": 11200,
    "bottles": [
      [
        "brown",
        "red",
        "red",
        "yellow"
      ],
      [
        "brown",
        "orange",
        "red",
        "orange"
      ],
      [
        "maroon",
        "brown",
        "brown",
        "white"
      ],
      [
        "maroon",
        "yellow",
        "orange",
        "orange"
      ],
      [
        "yellow",
        "red",
        "maroon",
        "white"
      ],
      [
        "white",
        "maroon",
        "white",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 24,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 20,
    "maxScore": 11600,
    "bottles": [
      [
        "brown",
        "maroon",
        "brown",
        "red"
      ],
      [
        "orange",
        "white",
        "maroon",
        "orange"
      ],
      [
        "brown",
        "white",
        "yellow",
        "red"
      ],
      [
        "orange",
        "yellow",
        "brown",
        "white"
      ],
      [
        "orange",
        "maroon",
        "red",
        "white"
      ],
      [
        "red",
        "maroon",
        "yellow",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 25,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 16,
    "maxScore": 12000,
    "bottles": [
      [
        "orange",
        "orange",
        "maroon",
        "white"
      ],
      [
        "orange",
        "maroon",
        "yellow",
        "yellow"
      ],
      [
        "red",
        "yellow",
        "brown",
        "brown"
      ],
      [
        "red",
        "red",
        "brown",
        "yellow"
      ],
      [
        "brown",
        "white",
        "red",
        "white"
      ],
      [
        "white",
        "maroon",
        "maroon",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 26,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 17,
    "maxScore": 12400,
    "bottles": [
      [
        "orange",
        "red",
        "brown",
        "brown"
      ],
      [
        "yellow",
        "white",
        "yellow",
        "red"
      ],
      [
        "white",
        "maroon",
        "orange",
        "orange"
      ],
      [
        "white",
        "white",
        "maroon",
        "maroon"
      ],
      [
        "brown",
        "yellow",
        "brown",
        "maroon"
      ],
      [
        "red",
        "orange",
        "yellow",
        "red"
      ],
      [],
      []
    ]
  },
  {
    "level": 27,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 19,
    "maxScore": 12800,
    "bottles": [
      [
        "red",
        "red",
        "white",
        "red"
      ],
      [
        "brown",
        "orange",
        "yellow",
        "maroon"
      ],
      [
        "white",
        "orange",
        "brown",
        "yellow"
      ],
      [
        "orange",
        "white",
        "brown",
        "maroon"
      ],
      [
        "yellow",
        "maroon",
        "brown",
        "orange"
      ],
      [
        "red",
        "maroon",
        "yellow",
        "white"
      ],
      [],
      []
    ]
  },
  {
    "level": 28,
    "colorsCount": 6,
    "emptyBottles": 2,
    "minMoves": 16,
    "maxScore": 13200,
    "bottles": [
      [
        "red",
        "yellow",
        "yellow",
        "white"
      ],
      [
        "red",
        "maroon",
        "maroon",
        "yellow"
      ],
      [
        "maroon",
        "brown",
        "maroon",
        "white"
      ],
      [
        "brown",
        "red",
        "brown",
        "orange"
      ],
      [
        "orange",
        "brown",
        "red",
        "yellow"
      ],
      [
        "orange",
        "orange",
        "white",
        "white"
      ],
      [],
      []
    ]
  },
  {
    "level": 29,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 23,
    "maxScore": 13600,
    "bottles": [
      [
        "red",
        "blue",
        "orange",
        "orange"
      ],
      [
        "white",
        "red",
        "yellow",
        "maroon"
      ],
      [
        "brown",
        "white",
        "maroon",
        "brown"
      ],
      [
        "red",
        "orange",
        "blue",
        "brown"
      ],
      [
        "yellow",
        "orange",
        "white",
        "blue"
      ],
      [
        "red",
        "maroon",
        "blue",
        "brown"
      ],
      [
        "maroon",
        "yellow",
        "white",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 30,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 20,
    "maxScore": 14000,
    "bottles": [
      [
        "red",
        "red",
        "orange",
        "brown"
      ],
      [
        "blue",
        "blue",
        "red",
        "blue"
      ],
      [
        "white",
        "brown",
        "brown",
        "maroon"
      ],
      [
        "orange",
        "yellow",
        "maroon",
        "orange"
      ],
      [
        "orange",
        "maroon",
        "white",
        "yellow"
      ],
      [
        "blue",
        "white",
        "brown",
        "red"
      ],
      [
        "yellow",
        "white",
        "maroon",
        "yellow"
      ],
      [],
      []
    ]
  },
  {
    "level": 31,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 22,
    "maxScore": 14400,
    "bottles": [
      [
        "yellow",
        "brown",
        "red",
        "orange"
      ],
      [
        "red",
        "white",
        "brown",
        "blue"
      ],
      [
        "blue",
        "white",
        "orange",
        "blue"
      ],
      [
        "blue",
        "brown",
        "brown",
        "red"
      ],
      [
        "maroon",
        "orange",
        "yellow",
        "red"
      ],
      [
        "maroon",
        "yellow",
        "white",
        "orange"
      ],
      [
        "yellow",
        "white",
        "maroon",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 32,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 22,
    "maxScore": 14800,
    "bottles": [
      [
        "white",
        "blue",
        "maroon",
        "white"
      ],
      [
        "maroon",
        "white",
        "blue",
        "brown"
      ],
      [
        "red",
        "yellow",
        "blue",
        "brown"
      ],
      [
        "orange",
        "maroon",
        "maroon",
        "yellow"
      ],
      [
        "brown",
        "red",
        "orange",
        "white"
      ],
      [
        "yellow",
        "orange",
        "blue",
        "brown"
      ],
      [
        "red",
        "yellow",
        "red",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 33,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 21,
    "maxScore": 15200,
    "bottles": [
      [
        "white",
        "orange",
        "yellow",
        "red"
      ],
      [
        "red",
        "maroon",
        "white",
        "orange"
      ],
      [
        "blue",
        "blue",
        "brown",
        "red"
      ],
      [
        "maroon",
        "yellow",
        "maroon",
        "yellow"
      ],
      [
        "blue",
        "brown",
        "yellow",
        "maroon"
      ],
      [
        "brown",
        "orange",
        "brown",
        "red"
      ],
      [
        "orange",
        "blue",
        "white",
        "white"
      ],
      [],
      []
    ]
  },
  {
    "level": 34,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 22,
    "maxScore": 15600,
    "bottles": [
      [
        "brown",
        "orange",
        "red",
        "yellow"
      ],
      [
        "white",
        "maroon",
        "blue",
        "white"
      ],
      [
        "yellow",
        "maroon",
        "yellow",
        "white"
      ],
      [
        "blue",
        "brown",
        "red",
        "brown"
      ],
      [
        "white",
        "blue",
        "orange",
        "orange"
      ],
      [
        "yellow",
        "maroon",
        "brown",
        "red"
      ],
      [
        "maroon",
        "red",
        "blue",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 35,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 18,
    "maxScore": 16000,
    "bottles": [
      [
        "blue",
        "brown",
        "yellow",
        "orange"
      ],
      [
        "blue",
        "maroon",
        "maroon",
        "red"
      ],
      [
        "yellow",
        "yellow",
        "red",
        "yellow"
      ],
      [
        "blue",
        "white",
        "blue",
        "orange"
      ],
      [
        "brown",
        "white",
        "white",
        "brown"
      ],
      [
        "maroon",
        "maroon",
        "red",
        "brown"
      ],
      [
        "orange",
        "orange",
        "red",
        "white"
      ],
      [],
      []
    ]
  },
  {
    "level": 36,
    "colorsCount": 7,
    "emptyBottles": 2,
    "minMoves": 18,
    "maxScore": 16400,
    "bottles": [
      [
        "yellow",
        "maroon",
        "white",
        "white"
      ],
      [
        "yellow",
        "yellow",
        "blue",
        "blue"
      ],
      [
        "red",
        "orange",
        "orange",
        "brown"
      ],
      [
        "brown",
        "brown",
        "orange",
        "red"
      ],
      [
        "brown",
        "white",
        "white",
        "orange"
      ],
      [
        "maroon",
        "blue",
        "red",
        "blue"
      ],
      [
        "red",
        "maroon",
        "yellow",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 37,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 26,
    "maxScore": 16800,
    "bottles": [
      [
        "maroon",
        "yellow",
        "maroon",
        "brown"
      ],
      [
        "red",
        "orange",
        "brown",
        "blue"
      ],
      [
        "teal",
        "orange",
        "maroon",
        "teal"
      ],
      [
        "maroon",
        "white",
        "red",
        "yellow"
      ],
      [
        "yellow",
        "orange",
        "brown",
        "red"
      ],
      [
        "white",
        "teal",
        "white",
        "blue"
      ],
      [
        "white",
        "blue",
        "blue",
        "brown"
      ],
      [
        "red",
        "orange",
        "yellow",
        "teal"
      ],
      [],
      []
    ]
  },
  {
    "level": 38,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 26,
    "maxScore": 17200,
    "bottles": [
      [
        "orange",
        "maroon",
        "white",
        "teal"
      ],
      [
        "orange",
        "blue",
        "teal",
        "orange"
      ],
      [
        "brown",
        "white",
        "red",
        "yellow"
      ],
      [
        "blue",
        "orange",
        "brown",
        "maroon"
      ],
      [
        "red",
        "teal",
        "brown",
        "maroon"
      ],
      [
        "white",
        "brown",
        "white",
        "yellow"
      ],
      [
        "yellow",
        "red",
        "blue",
        "maroon"
      ],
      [
        "teal",
        "yellow",
        "blue",
        "red"
      ],
      [],
      []
    ]
  },
  {
    "level": 39,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 23,
    "maxScore": 17600,
    "bottles": [
      [
        "blue",
        "blue",
        "red",
        "white"
      ],
      [
        "brown",
        "teal",
        "yellow",
        "orange"
      ],
      [
        "maroon",
        "red",
        "orange",
        "teal"
      ],
      [
        "brown",
        "maroon",
        "orange",
        "blue"
      ],
      [
        "red",
        "white",
        "white",
        "yellow"
      ],
      [
        "yellow",
        "maroon",
        "blue",
        "brown"
      ],
      [
        "red",
        "yellow",
        "orange",
        "white"
      ],
      [
        "teal",
        "teal",
        "brown",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 40,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 27,
    "maxScore": 18000,
    "bottles": [
      [
        "blue",
        "red",
        "white",
        "yellow"
      ],
      [
        "teal",
        "red",
        "blue",
        "brown"
      ],
      [
        "white",
        "red",
        "teal",
        "maroon"
      ],
      [
        "blue",
        "orange",
        "brown",
        "white"
      ],
      [
        "teal",
        "yellow",
        "orange",
        "brown"
      ],
      [
        "blue",
        "red",
        "white",
        "teal"
      ],
      [
        "yellow",
        "maroon",
        "brown",
        "yellow"
      ],
      [
        "maroon",
        "orange",
        "maroon",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 41,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 25,
    "maxScore": 18400,
    "bottles": [
      [
        "white",
        "yellow",
        "blue",
        "teal"
      ],
      [
        "white",
        "red",
        "orange",
        "orange"
      ],
      [
        "blue",
        "maroon",
        "maroon",
        "yellow"
      ],
      [
        "teal",
        "brown",
        "yellow",
        "orange"
      ],
      [
        "blue",
        "white",
        "maroon",
        "orange"
      ],
      [
        "brown",
        "maroon",
        "teal",
        "red"
      ],
      [
        "red",
        "white",
        "yellow",
        "red"
      ],
      [
        "brown",
        "teal",
        "brown",
        "blue"
      ],
      [],
      []
    ]
  },
  {
    "level": 42,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 19,
    "maxScore": 18800,
    "bottles": [
      [
        "blue",
        "blue",
        "brown",
        "maroon"
      ],
      [
        "brown",
        "brown",
        "orange",
        "orange"
      ],
      [
        "maroon",
        "orange",
        "orange",
        "white"
      ],
      [
        "white",
        "red",
        "yellow",
        "white"
      ],
      [
        "teal",
        "teal",
        "red",
        "brown"
      ],
      [
        "white",
        "yellow",
        "yellow",
        "blue"
      ],
      [
        "red",
        "red",
        "yellow",
        "blue"
      ],
      [
        "teal",
        "maroon",
        "maroon",
        "teal"
      ],
      [],
      []
    ]
  },
  {
    "level": 43,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 25,
    "maxScore": 19200,
    "bottles": [
      [
        "yellow",
        "yellow",
        "red",
        "maroon"
      ],
      [
        "white",
        "teal",
        "blue",
        "teal"
      ],
      [
        "orange",
        "white",
        "blue",
        "white"
      ],
      [
        "orange",
        "red",
        "orange",
        "blue"
      ],
      [
        "brown",
        "teal",
        "brown",
        "brown"
      ],
      [
        "teal",
        "maroon",
        "orange",
        "yellow"
      ],
      [
        "blue",
        "maroon",
        "brown",
        "red"
      ],
      [
        "yellow",
        "white",
        "maroon",
        "red"
      ],
      [],
      []
    ]
  },
  {
    "level": 44,
    "colorsCount": 8,
    "emptyBottles": 2,
    "minMoves": 23,
    "maxScore": 19600,
    "bottles": [
      [
        "white",
        "teal",
        "blue",
        "brown"
      ],
      [
        "maroon",
        "maroon",
        "teal",
        "blue"
      ],
      [
        "white",
        "blue",
        "teal",
        "yellow"
      ],
      [
        "brown",
        "maroon",
        "maroon",
        "red"
      ],
      [
        "yellow",
        "yellow",
        "red",
        "white"
      ],
      [
        "red",
        "orange",
        "white",
        "brown"
      ],
      [
        "orange",
        "blue",
        "yellow",
        "brown"
      ],
      [
        "red",
        "teal",
        "orange",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 45,
    "colorsCount": 9,
    "emptyBottles": 2,
    "minMoves": 27,
    "maxScore": 20000,
    "bottles": [
      [
        "maroon",
        "yellow",
        "brown",
        "blue"
      ],
      [
        "orange",
        "blue",
        "yellow",
        "purple"
      ],
      [
        "white",
        "blue",
        "yellow",
        "purple"
      ],
      [
        "white",
        "teal",
        "red",
        "maroon"
      ],
      [
        "purple",
        "purple",
        "brown",
        "brown"
      ],
      [
        "red",
        "orange",
        "orange",
        "red"
      ],
      [
        "maroon",
        "teal",
        "orange",
        "teal"
      ],
      [
        "red",
        "white",
        "maroon",
        "teal"
      ],
      [
        "yellow",
        "blue",
        "white",
        "brown"
      ],
      [],
      []
    ]
  },
  {
    "level": 46,
    "colorsCount": 9,
    "emptyBottles": 2,
    "minMoves": 24,
    "maxScore": 20400,
    "bottles": [
      [
        "yellow",
        "yellow",
        "yellow",
        "blue"
      ],
      [
        "white",
        "red",
        "teal",
        "teal"
      ],
      [
        "maroon",
        "orange",
        "maroon",
        "blue"
      ],
      [
        "orange",
        "brown",
        "brown",
        "brown"
      ],
      [
        "purple",
        "purple",
        "red",
        "teal"
      ],
      [
        "maroon",
        "maroon",
        "orange",
        "brown"
      ],
      [
        "purple",
        "red",
        "white",
        "red"
      ],
      [
        "teal",
        "purple",
        "blue",
        "white"
      ],
      [
        "orange",
        "blue",
        "yellow",
        "white"
      ],
      [],
      []
    ]
  },
  {
    "level": 47,
    "colorsCount": 9,
    "emptyBottles": 2,
    "minMoves": 25,
    "maxScore": 20800,
    "bottles": [
      [
        "purple",
        "red",
        "blue",
        "orange"
      ],
      [
        "brown",
        "purple",
        "blue",
        "blue"
      ],
      [
        "orange",
        "maroon",
        "red",
        "yellow"
      ],
      [
        "brown",
        "white",
        "white",
        "teal"
      ],
      [
        "maroon",
        "red",
        "purple",
        "brown"
      ],
      [
        "white",
        "purple",
        "white",
        "yellow"
      ],
      [
        "maroon",
        "teal",
        "teal",
        "teal"
      ],
      [
        "yellow",
        "yellow",
        "brown",
        "orange"
      ],
      [
        "maroon",
        "orange",
        "red",
        "blue"
      ],
      [],
      []
    ]
  },
  {
    "level": 48,
    "colorsCount": 9,
    "emptyBottles": 2,
    "minMoves": 27,
    "maxScore": 21200,
    "bottles": [
      [
        "red",
        "red",
        "yellow",
        "orange"
      ],
      [
        "brown",
        "purple",
        "purple",
        "red"
      ],
      [
        "white",
        "purple",
        "blue",
        "red"
      ],
      [
        "maroon",
        "brown",
        "teal",
        "white"
      ],
      [
        "maroon",
        "teal",
        "maroon",
        "orange"
      ],
      [
        "blue",
        "yellow",
        "white",
        "teal"
      ],
      [
        "teal",
        "orange",
        "orange",
        "yellow"
      ],
      [
        "brown",
        "blue",
        "white",
        "yellow"
      ],
      [
        "blue",
        "purple",
        "brown",
        "maroon"
      ],
      [],
      []
    ]
  },
  {
    "level": 49,
    "colorsCount": 9,
    "emptyBottles": 2,
    "minMoves": 28,
    "maxScore": 21600,
    "bottles": [
      [
        "red",
        "blue",
        "brown",
        "red"
      ],
      [
        "red",
        "brown",
        "white",
        "purple"
      ],
      [
        "purple",
        "teal",
        "orange",
        "white"
      ],
      [
        "maroon",
        "yellow",
        "purple",
        "purple"
      ],
      [
        "brown",
        "white",
        "yellow",
        "maroon"
      ],
      [
        "blue",
        "red",
        "teal",
        "teal"
      ],
      [
        "blue",
        "white",
        "maroon",
        "blue"
      ],
      [
        "brown",
        "orange",
        "yellow",
        "orange"
      ],
      [
        "yellow",
        "maroon",
        "teal",
        "orange"
      ],
      [],
      []
    ]
  },
  {
    "level": 50,
    "colorsCount": 9,
    "emptyBottles": 2,
    "minMoves": 28,
    "maxScore": 22000,
    "bottles": [
      [
        "white",
        "blue",
        "orange",
        "teal"
      ],
      [
        "white",
        "red",
        "red",
        "blue"
      ],
      [
        "purple",
        "orange",
        "red",
        "red"
      ],
      [
        "yellow",
        "orange",
        "maroon",
        "yellow"
      ],
      [
        "maroon",
        "maroon",
        "teal",
        "purple"
      ],
      [
        "yellow",
        "white",
        "orange",
        "yellow"
      ],
      [
        "brown",
        "blue",
        "purple",
        "brown"
      ],
      [
        "brown",
        "teal",
        "teal",
        "blue"
      ],
      [
        "maroon",
        "white",
        "purple",
        "brown"
      ],
      [],
      []
    ]
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { COLOR_PALETTE, LEVELS_DATA };
}
